### ISSUE TITLE
Add maxNativeMemoryLimitInBytes option for S3 CRT client

### ISSUE THREAD

**Issue by vladimirfx** [quarkiverse/quarkus-amazon-services#1197]
Context: https://github.com/aws/aws-sdk-java-v2/issues/4034

Currently, switching to the CRT client requires much more memory (especially for native build) and custom build options such `quarkus.native.additional-build-args=-R:MaximumHeapSizePercent=50` to be used successfully. Strarting from version 0.29.7 Amazon provides a hard limiting option `maxNativeMemoryLimitInBytes ` for the CRT client that is very useful for cases where high throughput is not needed.

**Comment by vladimirfx** [comment]
The current workaround that partially helps:

```yaml
  s3:
    sync-client:
      type: aws-crt
    crt-client:
      target-throughput-in-gbps: 1
      max-concurrency: 2
```

**Comment by scrocquesel** [comment]
@vladimirfx would you like to propose a PR ?
I guess it is something that need to be added in https://github.com/quarkiverse/quarkus-amazon-services/blob/main/s3/runtime/src/main/java/io/quarkus/amazon/s3/runtime/S3CrtConfig.java and set up in the recorder https://github.com/quarkiverse/quarkus-amazon-services/blob/6a3b18689c9e2f59bad2c8bd7629c8a99e1f3128/s3/runtime/src/main/java/io/quarkus/amazon/s3/runtime/S3CrtRecorder.java#L39

**Comment by vladimirfx** [comment]
I will do

**Comment by vladimirfx** [comment]
Thank you!

Unfortunately, it does not work at all. Such config leads to native memory consumption over 200Mb and OOMError for 1 file download of several gigabytes:

```yaml
  s3:
    sync-client:
      type: aws-crt
    crt-client:
      target-throughput-in-gbps: 0.1
      max-concurrency: 1
      max-native-memory-limit-in-bytes: 2097152
```

Related tickets are just closed by inactivity: https://github.com/aws/aws-sdk-java-v2/issues/4168
